# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(731, 460) #设置初始大小
        MainWindow.setAutoFillBackground(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(15, 10, 700, 421))
        font = QtGui.QFont()
        font.setFamily("Hannotate TC")
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Search = QtWidgets.QWidget() 
        self.tab_Search.setObjectName("tab_Search")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_Search)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 671, 371))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_Search = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Hannotate TC")
        font.setPointSize(18)
        self.label_Search.setFont(font)
        self.label_Search.setObjectName("label_Search")
        self.horizontalLayout_3.addWidget(self.label_Search)
        self.lineEdit_Search = QtWidgets.QLineEdit(self.verticalLayoutWidget_2) 
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Search.sizePolicy().hasHeightForWidth())
        self.lineEdit_Search.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Hannotate TC")
        font.setPointSize(14)
        self.lineEdit_Search.setFont(font)
        self.lineEdit_Search.setText("") #lineEdit_Search
        self.lineEdit_Search.setObjectName("lineEdit_Search")
        self.horizontalLayout_3.addWidget(self.lineEdit_Search)
        self.pushButton_Search = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Taipei Sans TC Beta")
        font.setPointSize(13)
        self.pushButton_Search.setFont(font)
        self.pushButton_Search.setObjectName("pushButton_Search")
        self.horizontalLayout_3.addWidget(self.pushButton_Search)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.listView_Search = QtWidgets.QListView(self.verticalLayoutWidget_2)
        self.listView_Search.setProperty("showDropIndicator", False)
        self.listView_Search.setObjectName("listView_Search")
        self.verticalLayout_2.addWidget(self.listView_Search)
        self.tabWidget.addTab(self.tab_Search, "")
        self.tab_Download = QtWidgets.QWidget()
        self.tab_Download.setObjectName("tab_Download")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_Download)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 671, 371))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_Download = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Hannotate TC")
        font.setPointSize(18)
        self.label_Download.setFont(font)
        self.label_Download.setObjectName("label_Download")
        self.horizontalLayout_5.addWidget(self.label_Download)
        self.lineEdit_Download = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Download.sizePolicy().hasHeightForWidth())
        self.lineEdit_Download.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Hannotate TC")
        font.setPointSize(14)
        self.lineEdit_Download.setFont(font)
        self.lineEdit_Download.setText("")
        self.lineEdit_Download.setObjectName("lineEdit_Download")
        self.horizontalLayout_5.addWidget(self.lineEdit_Download)
        self.pushButton_Download = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Taipei Sans TC Beta")
        font.setPointSize(13)
        self.pushButton_Download.setFont(font)
        self.pushButton_Download.setObjectName("pushButton_Download")
        self.horizontalLayout_5.addWidget(self.pushButton_Download)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.listView_Download = QtWidgets.QListView(self.verticalLayoutWidget_4)
        self.listView_Download.setProperty("showDropIndicator", False)
        self.listView_Download.setObjectName("listView_Download")
        self.verticalLayout_4.addWidget(self.listView_Download)
        self.tabWidget.addTab(self.tab_Download, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 731, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuAnime1 = QtWidgets.QMenu(self.menuBar)
        self.menuAnime1.setObjectName("menuAnime1")
        MainWindow.setMenuBar(self.menuBar)
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.menuAnime1.addAction(self.action1)
        self.menuAnime1.addAction(self.action2)
        self.menuBar.addAction(self.menuAnime1.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Search.setText(_translate("MainWindow", "Key Word"))
        self.pushButton_Search.setText(_translate("MainWindow", "Go"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Search), _translate("MainWindow", "Anime1 ID Search"))
        self.label_Download.setText(_translate("MainWindow", "Anime1 ID"))
        self.pushButton_Download.setText(_translate("MainWindow", "Go"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Download), _translate("MainWindow", "Anime1 ID Download"))
        self.menuAnime1.setTitle(_translate("MainWindow", "Anime1"))
        self.action1.setText(_translate("MainWindow", "1"))
        self.action2.setText(_translate("MainWindow", "2"))